### PR TITLE
Refactored for cleaner Job creation method

### PR DESCRIPTION
**Pull request by nicklaw5**

### CODE REVIEW

**Comment by nicklaw5** [comment]
Sorry I mean to merge this into my master branch, not yours :disappointed:

Once I'm finished I can provide a PR for your version and you can merge it if you want :smile:

**Comment by nrempel** [comment]
Hey @nicklaw5 that sounds great, looks like there are many good improvements here.

Looking forward to looking at the PR

**Comment by nrempel** [comment]
@nicklaw5 would you be interested in submitting a pull request for your changes?

I'd be happy to also make you a collaborator.

There is another pending pull request, but I'd like to have that build on your refactor if you are interested in merging back into this branch.

**Comment by nicklaw5** [comment]
I was literally just considering this before getting you comment.

The only thing is, I haven't had time to re-write the tests. I can submit my changes if you want to take a stab at the tests? Sorry I just don't have time to do it in the next few weeks.

Also, I was planning on adding kue's [failure backoff](https://github.com/Automattic/kue#failure-backoff) capability, but again, just haven't got around to it yet. I guess that can be added at a later date no doubt.

**Comment by nrempel** [comment]
Nice 😀

If you open up a new pull request, we can work together or get help from others to get the tests up to date. Even if it doesn't get merged right away, it's nice to have it pending so everyone can see where things are at.

Thanks! 😊

**Comment by nicklaw5** [comment]
Ok will submit my changes tomorrow.

**Pull request closed without merging**
